apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: frontend-container
          env:
            - name: SET_BY_KUSTOMIZE
              value: "true"
            - name: REDIS_VERSION
              value: "prod" 